pull_request_rules:
  - name: Automatic merge on Travis success if author
    conditions:
      - author~=^(MRVMV|depfu\[bot\]|dependabot(|-preview)\[bot\])$
      - -label~=.*\bwip\b.*
      - status-success=Travis CI - Pull Request
      - status-success=CodeQL
    actions:
      merge:
        method: merge
  - name: say hi on new contribution
    conditions:
      - -author~=^(MRVMV|depfu\[bot\]|dependabot(|-preview)\[bot\])$
    actions:
        comment:
          message: |
              Welcome {{author}} to our great project!
              We're delight to have you onboard <3
