pull_request_rules:
  - name: Automatic merge on Travis success if author
    conditions:
      - author~=^(mrvmv|depfu|dependabot(|-preview)\[bot\])$
      - status-success=Travis CI - Pull Request
      - -label~=.*\bwip\b.*
    actions:
      merge:
        method: merge
  - name: say hi on new contribution
    conditions:
      - -author~=^(@mrvmv|depfu|dependabot(|-preview)\[bot\])$
    actions:
        comment:
          message: |
              Welcome to our great project!
              We're delight to have you onboard <3
