pull_request_rules:
  - name: Automatic merge on Travis success if author
    conditions:
      - author~=^(MRVMV|depfu\[bot\]|dependabot(|-preview)\[bot\])$
      - -label~=.*\bwip\b.*
      - status-success=CodeQL
      - status-success=Analyze (javascript)
      - status-success=build (12.x)
      - status-success=build (14.x)
      - status-success=build (15.x)
    actions:
      merge:
        method: merge
  - name: say hi on new contribution
    conditions:
      - -author~=^(MRVMV|depfu\[bot\]|dependabot(|-preview)\[bot\])$
    actions:
      comment:
        message: |
          Welcome {{author}} to our great project!
          We're delight to have you onboard <3
