language: node_js
node_js:
  - 14
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: 14
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        script:
            - yarn global add semantic-release
            - yarn semantic-release
        on:
          branch: main
