language: node_js
node_js:
  - 14.13.0
  - 13.14.0
  - 12.18.4
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: 14
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        script:
          - yarn install --production=false && yarn semantic-release
        on:
          branch: main
